[git]
commitMessage = "chore: release v${version}"
tagName = "v${version}"
requireCleanWorkingDir = false
requireBranch = "main"

[github]
release = true
releaseName = "v${version}"

[npm]
publish = false

[plugins."@release-it/conventional-changelog"]
preset = "angular"
infile = "CHANGELOG.md"
